# -*- mode: ruby -*-
# vi: set ft=ruby :

personalization = File.expand_path("../Personalization", __FILE__)
load personalization

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    if Vagrant.has_plugin?("vagrant-vbguest")
      config.vbguest.auto_update = false
    end

    if Vagrant.has_plugin?("vagrant-cachier")
       config.cache.scope = :box # cache at the base box level

       # setup apt-get cache
       config.cache.enable :apt
       
       if $use_nfs
         config.cache.synced_folder_opts = {
           type: :nfs,
           mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
         }
       end
    else
       print "vagrant-cachier plugin has not been found."
       print "You can install it using `vagrant plugin install vagrant-cachier`"
    end

    config.vm.box = $box

    config.vm.box_url = $box_url

    config.vm.host_name = "stackinabox"

    # eth1, this will be OpenStacks's "management" network
    config.vm.network "private_network", ip: "192.168.27.100", adapter_ip: "192.168.27.1", netmask: "255.255.255.0", auto_config: true

    # eth2, this will be OpenStack's "public" network
    config.vm.network "private_network", ip: "172.24.4.225", adapter_ip: "172.24.4.225", netmask: "255.255.255.0", auto_config: false

    config.vm.synced_folder "..", "/vagrant", :nfs => $use_nfs

    config.ssh.forward_agent = true

    config.ssh.insert_key = false

    config.vm.provider :virtualbox do |vb|
        # vb.gui = true
        # Use VBoxManage to customize the VM.
        vb.customize ["modifyvm", :id, "--ioapic", "on"] # turn on I/O APIC
        vb.customize ["modifyvm", :id, "--cpus", "#{$cpus}"] # set number of vcpus
        vb.customize ["modifyvm", :id, "--memory", "#{$memory}"] # set amount of memory allocated vm memory
        vb.customize ["modifyvm", :id, "--hwvirtex", "on"] # turn on host hardware virtualization extensions (VT-x|AMD-V)
        vb.customize ["modifyvm", :id, "--ostype", "Ubuntu_64"] # set guest OS type
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"] # enables DNS resolution from guest using host's DNS
        vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"] # turn on promiscuous mode on nic 3
        vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
        vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
        vb.customize ["modifyvm", :id, "--nictype3", "virtio"]
        vb.customize ["modifyvm", :id, "--longmode", "on"] # enables long mode (64 bit mode in GUEST OS)
        vb.customize ["modifyvm", :id, "--hpet", "on"] # enables a High Precision Event Timer (HPET)
        vb.customize ["modifyvm", :id, "--nestedpaging", "on"] # if --hwvirtex is on, this enables nested paging
        vb.customize ["modifyvm", :id, "--largepages", "on"] # if --hwvirtex & --nestedpaging are on
        vb.customize ["modifyvm", :id, "--vtxvpid", "on"] # if --hwvirtex on
        vb.customize ["modifyvm", :id, "--vtxux", "on"] # if --vtux on (Intel VT-x only) enables unrestricted guest mode
        vb.customize ["modifyvm", :id, "--boot1", "disk"] # tells vm to boot from disk only
        vb.customize ["modifyvm", :id, "--audio", "none"]
        vb.customize ["modifyvm", :id, "--clipboard", "disabled"]
        vb.customize ["modifyvm", :id, "--usbehci", "off"]
        vb.customize ["modifyvm", :id, "--vrde", "off"]
    end
end
